# Nixpacks configuration for Railway
[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install] 
cmds = ["npm install --production"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "node simple-agent.js"