[build]
builder = "nixpacks"

[deploy]
startCommand = "node simple-agent.js"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/status"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_NODE_VERSION = "18"